[package]
name = "veldora"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.9.1"
sha-1 = "0.9.8"
sha2 = "0.9.8"
colored = "2.0.0"
pdf = "0.7.2"
zip = "0.5.13"
